# Generated by Django 4.1.7 on 2023-03-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('built', models.IntegerField()),
                ('description', models.TextField(max_length=250)),
                ('arctype', models.CharField(choices=[('M', 'Modern'), ('MCM', 'Midcentury Modern'), ('NC', 'Neo Classical'), ('R', 'California Romanza'), ('CR', 'Craftsman'), ('COL', 'Colonial Revival'), ('SP', 'Spanish'), ('CHT', 'Châteauesque')], default='M', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guestnum', models.IntegerField(max_length=3)),
                ('bedrooms', models.IntegerField(max_length=3)),
                ('bathrooms', models.IntegerField(max_length=3)),
                ('availabile', models.BooleanField()),
            ],
        ),
    ]
