# Generated by Django 4.1.7 on 2023-03-08 19:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yearbuilt', models.IntegerField()),
                ('description', models.TextField(max_length=800)),
                ('arc_type', models.CharField(choices=[('Modern', 'Modern'), ('Midcentury Modern', 'Midcentury Modern'), ('Neo Classica', 'Neo Classical'), ('California Romanza', 'California Romanza'), ('Craftsman', 'Craftsman'), ('Colonial Revival', 'Colonial Revival'), ('Spanish', 'Spanish'), ('Châteauesque', 'Châteauesque')], default='Modern', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guest_num', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('available', models.BooleanField()),
                ('main_img', models.CharField(max_length=200)),
                ('second_img', models.CharField(max_length=200)),
                ('third_img', models.CharField(max_length=200)),
                ('fourth_img', models.CharField(max_length=200)),
                ('fifth_img', models.CharField(max_length=200)),
                ('amenities', models.ManyToManyField(to='main_app.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2023, 3, 8, 19, 8, 53, 121105), verbose_name='Booking Date')),
                ('checkin', models.DateField(default=datetime.datetime(2023, 3, 8, 19, 8, 53, 121118), verbose_name='Checkin Date')),
                ('checkout', models.DateField(default=datetime.datetime(2023, 3, 8, 19, 8, 53, 121123), verbose_name='Checkout Date')),
                ('guests', models.IntegerField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
