# Generated by Django 4.1.7 on 2023-03-08 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Feature',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='amenities',
            new_name='features',
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2023, 3, 8, 20, 4, 49, 983522), verbose_name='Checkin Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2023, 3, 8, 20, 4, 49, 983526), verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 8, 20, 4, 49, 983511), verbose_name='Booking Date'),
        ),
    ]
