# Generated by Django 4.1.7 on 2023-03-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_listing_bathrooms_alter_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='arctype',
            new_name='arc_type',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='availabile',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='built',
            new_name='guest_num',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='guestnum',
            new_name='yearbuilt',
        ),
    ]
