# Generated by Django 4.1.7 on 2023-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_arctype_listing_arc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='second_img',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='third_img',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
