# Generated by Django 4.1.7 on 2023-03-10 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_booking_checkin_alter_booking_checkout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['checkin']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 1, 4, 29, 924139), verbose_name='Checkin Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 1, 4, 29, 924142), verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 1, 4, 29, 924129), verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='arc_type',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Midcentury Modern', 'Midcentury Modern'), ('Neo Classical', 'Neo Classical'), ('California Romanza', 'California Romanza'), ('Craftsman', 'Craftsman'), ('Colonial Revival', 'Colonial Revival'), ('Spanish', 'Spanish'), ('Châteauesque', 'Châteauesque')], default='Modern', max_length=50),
        ),
    ]
