# Generated by Django 4.1.7 on 2023-03-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_listing_main_img_listing_second_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='arc_type',
            field=models.CharField(choices=[('Modern', 'Modern'), ('MCM', 'Midcentury Modern'), ('NC', 'Neo Classical'), ('R', 'California Romanza'), ('CR', 'Craftsman'), ('COL', 'Colonial Revival'), ('SP', 'Spanish'), ('CHT', 'Châteauesque')], default='Modern', max_length=20),
        ),
    ]
