# Generated by Django 4.1.7 on 2023-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_listing_arc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='arc_type',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Midcentury Modern', 'Midcentury Modern'), ('Neo Classica', 'Neo Classical'), ('California Romanza', 'California Romanza'), ('Craftsma', 'Craftsman'), ('Colonial Revival', 'Colonial Revival'), ('Spanish', 'Spanish'), ('Châteauesque', 'Châteauesque')], default='Modern', max_length=50),
        ),
    ]
