# Generated by Django 4.1.7 on 2023-03-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_listing_arc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='fifth_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='fourth_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
