# Generated by Django 4.1.7 on 2023-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default='2023-03-03', verbose_name='Booking Date'),
            preserve_default=False,
        ),
    ]
