# Generated by Django 4.1.7 on 2023-03-07 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 19, 41, 57, 779295), verbose_name='Checkin Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 19, 41, 57, 779306), verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='arc_type',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Midcentury Modern', 'Midcentury Modern'), ('Neo Classica', 'Neo Classical'), ('California Romanza', 'California Romanza'), ('Craftsman', 'Craftsman'), ('Colonial Revival', 'Colonial Revival'), ('Spanish', 'Spanish'), ('Châteauesque', 'Châteauesque')], default='Modern', max_length=50),
        ),
    ]
