# Generated by Django 4.1.7 on 2023-03-07 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_booking_checkin_date_booking_checkout_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 19, 46, 49, 350307), verbose_name='Checkin Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 19, 46, 49, 350316), verbose_name='Checkout Date'),
        ),
    ]
