# Generated by Django 4.1.7 on 2023-03-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_booking_checkin_alter_booking_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='arc_type',
            field=models.CharField(choices=[('Modern', 'Modern'), ('Midcentury Modern', 'Midcentury Modern'), ('Neo Classica', 'Neo Classical'), ('California Romanza', 'California Romanza'), ('Craftsma', 'Craftsman'), ('Colonial Revival', 'Colonial Revival'), ('Spanish', 'Spanish'), ('Châteauesque', 'Châteauesque')], default='Modern', max_length=50),
        ),
    ]
