# Generated by Django 4.1.7 on 2023-03-07 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_booking_checkin_remove_booking_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.date(2023, 3, 7), verbose_name='Checkin Date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.date(2023, 3, 7), verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 7), verbose_name='Booking Date'),
        ),
    ]
