# Generated by Django 4.1.7 on 2023-03-07 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_booking_checkin_alter_booking_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 23, 17, 45, 409189), verbose_name='Checkin Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 23, 17, 45, 409193), verbose_name='Checkout Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 7, 23, 17, 45, 409178), verbose_name='Booking Date'),
        ),
    ]
